/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package LesFormees;

/**
 *
 * @author lahcen
 */
public class JFrame_Menu extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Menu
     */
    public JFrame_Menu() {
        initComponents();
        jLabel_bord2.setVisible(false);
        jLabel_Pationt2.setVisible(false);
        jLabel_Service2.setVisible(false);
        jLabel_chercher2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Chercher = new javax.swing.JPanel();
        jLabel_bord1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_bord2 = new javax.swing.JLabel();
        jLabel_Pationt2 = new javax.swing.JLabel();
        jLabel_Pation1 = new javax.swing.JLabel();
        jLabel_Service2 = new javax.swing.JLabel();
        jLabel_Service1 = new javax.swing.JLabel();
        jLabel_chercher2 = new javax.swing.JLabel();
        jLabel_chercher1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Chercher.setBackground(new java.awt.Color(255, 102, 102));
        Chercher.setLayout(null);

        jLabel_bord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Borderent2.jpg"))); // NOI18N
        jLabel_bord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_bord1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_bord1MouseEntered(evt);
            }
        });
        Chercher.add(jLabel_bord1);
        jLabel_bord1.setBounds(110, 150, 108, 108);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setText("borderent");
        Chercher.add(jLabel1);
        jLabel1.setBounds(132, 265, 65, 15);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setText("Pationt");
        Chercher.add(jLabel6);
        jLabel6.setBounds(264, 265, 46, 15);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel7.setText("S.Orient");
        Chercher.add(jLabel7);
        jLabel7.setBounds(383, 265, 52, 15);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setText("Chercher");
        Chercher.add(jLabel8);
        jLabel8.setBounds(491, 265, 59, 15);

        jLabel_bord2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/borderent_Click.jpg"))); // NOI18N
        jLabel_bord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_bord2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_bord2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_bord2MouseExited(evt);
            }
        });
        Chercher.add(jLabel_bord2);
        jLabel_bord2.setBounds(110, 150, 108, 108);

        jLabel_Pationt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pation_Click.jpg"))); // NOI18N
        jLabel_Pationt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Pationt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Pationt2MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Pationt2MouseClicked(evt);
            }
        });
        Chercher.add(jLabel_Pationt2);
        jLabel_Pationt2.setBounds(230, 150, 110, 110);

        jLabel_Pation1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pationt2.jpg"))); // NOI18N
        jLabel_Pation1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Pation1MouseEntered(evt);
            }
        });
        Chercher.add(jLabel_Pation1);
        jLabel_Pation1.setBounds(230, 150, 108, 108);

        jLabel_Service2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/service_click.jpg"))); // NOI18N
        jLabel_Service2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Service2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Service2MouseExited(evt);
            }
        });
        Chercher.add(jLabel_Service2);
        jLabel_Service2.setBounds(350, 150, 110, 108);

        jLabel_Service1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Service.jpg"))); // NOI18N
        jLabel_Service1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Service1MouseEntered(evt);
            }
        });
        Chercher.add(jLabel_Service1);
        jLabel_Service1.setBounds(350, 150, 110, 108);

        jLabel_chercher2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chercher_Click.jpg"))); // NOI18N
        jLabel_chercher2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_chercher2MouseExited(evt);
            }
        });
        Chercher.add(jLabel_chercher2);
        jLabel_chercher2.setBounds(470, 150, 110, 110);

        jLabel_chercher1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chercher.jpg"))); // NOI18N
        jLabel_chercher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_chercher1MouseEntered(evt);
            }
        });
        Chercher.add(jLabel_chercher1);
        jLabel_chercher1.setBounds(470, 150, 120, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Chercher, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Chercher, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_bord1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bord1MouseEntered

        jLabel_bord1.setVisible(false);
        jLabel_bord2.setVisible(true);
    }//GEN-LAST:event_jLabel_bord1MouseEntered

    private void jLabel_bord2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bord2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_bord2MouseEntered

    private void jLabel_bord2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bord2MouseExited
        jLabel_bord1.setVisible(true);
        jLabel_bord2.setVisible(false);
    }//GEN-LAST:event_jLabel_bord2MouseExited

    private void jLabel_Pation1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Pation1MouseEntered

        jLabel_Pation1.setVisible(false);
        jLabel_Pationt2.setVisible(true);
    }//GEN-LAST:event_jLabel_Pation1MouseEntered

    private void jLabel_Pationt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Pationt2MouseEntered
      
    }//GEN-LAST:event_jLabel_Pationt2MouseEntered

    private void jLabel_Pationt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Pationt2MouseExited

         jLabel_Pation1.setVisible(true);
        jLabel_Pationt2.setVisible(false);
    }//GEN-LAST:event_jLabel_Pationt2MouseExited

    private void jLabel_Service1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Service1MouseEntered

        jLabel_Service1.setVisible(false);
        jLabel_Service2.setVisible(true);
    }//GEN-LAST:event_jLabel_Service1MouseEntered

    private void jLabel_Service2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Service2MouseExited

        jLabel_Service1.setVisible(true);
        jLabel_Service2.setVisible(false);
    }//GEN-LAST:event_jLabel_Service2MouseExited

    private void jLabel_chercher1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_chercher1MouseEntered

        jLabel_chercher1.setVisible(false);
        jLabel_chercher2.setVisible(true);
    }//GEN-LAST:event_jLabel_chercher1MouseEntered

    private void jLabel_chercher2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_chercher2MouseExited
      jLabel_chercher1.setVisible(true);
        jLabel_chercher2.setVisible(false);
    }//GEN-LAST:event_jLabel_chercher2MouseExited

    private void jLabel_bord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bord1MouseClicked

           
    }//GEN-LAST:event_jLabel_bord1MouseClicked

    private void jLabel_bord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bord2MouseClicked
         JFrame_Borderentt f=new JFrame_Borderentt();
            f.show();
    }//GEN-LAST:event_jLabel_bord2MouseClicked

    private void jLabel_Pationt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Pationt2MouseClicked

        JFrame_Pationt form=new JFrame_Pationt();
          form.setVisible(true);
          form.pack();
          form.setLocationRelativeTo(null);
          this.setVisible(false);
          form.setSize(1105, 600);
    }//GEN-LAST:event_jLabel_Pationt2MouseClicked

    private void jLabel_Service2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Service2MouseClicked

         JFrame_S_orient__Act_Medi form=new JFrame_S_orient__Act_Medi();
          form.setVisible(true);
          form.pack();
          form.setLocationRelativeTo(null);
          this.setVisible(false);
          form.setSize(1105, 600);
    }//GEN-LAST:event_jLabel_Service2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Chercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Pation1;
    private javax.swing.JLabel jLabel_Pationt2;
    private javax.swing.JLabel jLabel_Service1;
    private javax.swing.JLabel jLabel_Service2;
    private javax.swing.JLabel jLabel_bord1;
    private javax.swing.JLabel jLabel_bord2;
    private javax.swing.JLabel jLabel_chercher1;
    private javax.swing.JLabel jLabel_chercher2;
    // End of variables declaration//GEN-END:variables
}
