/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package LesFormees;
import javax.swing.*;

/**
 *
 * @author lahcen
 */
public class JFrame_Pationt extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Pationt
     */
    public JFrame_Pationt() {
        initComponents();
      jPanel_Modifier.setVisible(false);
      Panel_Entit_Modifier.setVisible(false);
      this.setSize(1105, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Modifier = new javax.swing.JPanel();
        Button_enregistrer = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextArea_Modifier_Observation = new javax.swing.JTextArea();
        RadioButton_Modifier_Sexe_Oui = new javax.swing.JRadioButton();
        RadioButton_Modifier_Sexe_Non = new javax.swing.JRadioButton();
        RadioButton_Modifier_Enfant_Non = new javax.swing.JRadioButton();
        RadioButton_Modifier_Enfant_Oui = new javax.swing.JRadioButton();
        Combobox_Modifier_Act_Medic = new javax.swing.JComboBox();
        RadioButton_Modifier_Consultation_Oui = new javax.swing.JRadioButton();
        RadioButton_Modifier_Consultation_Non = new javax.swing.JRadioButton();
        Combobox_Modifier_CIN = new javax.swing.JComboBox();
        txt_Modifier_Prenom = new javax.swing.JTextField();
        combobox__Modifier_S_Orient3 = new javax.swing.JComboBox();
        txt_Modifier_Nom = new javax.swing.JTextField();
        jPanel_Ajouter_Pationt = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_CIN = new javax.swing.JTextField();
        txt_Nom = new javax.swing.JTextField();
        txt_Prenom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        RadioButton_Enfant_Oui = new javax.swing.JRadioButton();
        RadioButton_Enfant_Nom = new javax.swing.JRadioButton();
        RadioButton_Sexe_Oui = new javax.swing.JRadioButton();
        RadioButton_Sexe_Nom = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Observation = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Button_Ajouter = new javax.swing.JButton();
        Button_Modifier = new javax.swing.JButton();
        Button_Supprimer = new javax.swing.JButton();
        Combobx_Service_Orient = new javax.swing.JComboBox();
        Combobx_ACT_Medical = new javax.swing.JComboBox();
        RadioButton_Consultation_Non = new javax.swing.JRadioButton();
        RadioButton_Consultation_Oui = new javax.swing.JRadioButton();
        jLabel_nouveau_service_orient = new javax.swing.JLabel();
        jLabel_nouveau_Acts = new javax.swing.JLabel();
        Combobx_ID_Bererent = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel_nouveau_ID_berderent = new javax.swing.JLabel();
        Panel_Entit_Modifier = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_Entit_Ajouter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Modifier.setBackground(new java.awt.Color(153, 255, 153));
        jPanel_Modifier.setMinimumSize(new java.awt.Dimension(12, 50));
        jPanel_Modifier.setPreferredSize(new java.awt.Dimension(437, 0));
        jPanel_Modifier.setLayout(null);

        Button_enregistrer.setBackground(new java.awt.Color(0, 204, 204));
        Button_enregistrer.setText("Supprimer");
        Button_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_enregistrerActionPerformed(evt);
            }
        });
        jPanel_Modifier.add(Button_enregistrer);
        Button_enregistrer.setBounds(490, 293, 102, 30);

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel24.setText("Nom :");
        jPanel_Modifier.add(jLabel24);
        jLabel24.setBounds(140, 60, 37, 15);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel25.setText("CIN :");
        jPanel_Modifier.add(jLabel25);
        jLabel25.setBounds(140, 30, 31, 15);

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel26.setText("Prenom :");
        jPanel_Modifier.add(jLabel26);
        jLabel26.setBounds(140, 90, 58, 15);

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel27.setText("S.Orient :");
        jPanel_Modifier.add(jLabel27);
        jLabel27.setBounds(140, 130, 60, 15);

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel28.setText("Consultation :");
        jPanel_Modifier.add(jLabel28);
        jLabel28.setBounds(140, 160, 89, 15);

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel29.setText("Act.Med :");
        jPanel_Modifier.add(jLabel29);
        jLabel29.setBounds(140, 200, 59, 15);

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel30.setText("Enfant :");
        jPanel_Modifier.add(jLabel30);
        jLabel30.setBounds(140, 240, 50, 15);

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel31.setText("Sexe :");
        jPanel_Modifier.add(jLabel31);
        jLabel31.setBounds(140, 260, 40, 23);

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel32.setText("Observation :");
        jPanel_Modifier.add(jLabel32);
        jLabel32.setBounds(130, 330, 87, 37);

        TextArea_Modifier_Observation.setBackground(new java.awt.Color(204, 255, 204));
        TextArea_Modifier_Observation.setColumns(20);
        TextArea_Modifier_Observation.setRows(5);
        jScrollPane4.setViewportView(TextArea_Modifier_Observation);

        jPanel_Modifier.add(jScrollPane4);
        jScrollPane4.setBounds(270, 290, 190, 120);

        RadioButton_Modifier_Sexe_Oui.setBackground(new java.awt.Color(153, 255, 153));
        RadioButton_Modifier_Sexe_Oui.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Modifier_Sexe_Oui.setText("Oui");
        RadioButton_Modifier_Sexe_Oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_Modifier_Sexe_OuiActionPerformed(evt);
            }
        });
        jPanel_Modifier.add(RadioButton_Modifier_Sexe_Oui);
        RadioButton_Modifier_Sexe_Oui.setBounds(270, 260, 47, 23);

        RadioButton_Modifier_Sexe_Non.setBackground(new java.awt.Color(153, 255, 153));
        RadioButton_Modifier_Sexe_Non.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Modifier_Sexe_Non.setText("Non");
        jPanel_Modifier.add(RadioButton_Modifier_Sexe_Non);
        RadioButton_Modifier_Sexe_Non.setBounds(330, 260, 51, 23);

        RadioButton_Modifier_Enfant_Non.setBackground(new java.awt.Color(153, 255, 153));
        RadioButton_Modifier_Enfant_Non.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Modifier_Enfant_Non.setText("Non");
        jPanel_Modifier.add(RadioButton_Modifier_Enfant_Non);
        RadioButton_Modifier_Enfant_Non.setBounds(330, 230, 51, 23);

        RadioButton_Modifier_Enfant_Oui.setBackground(new java.awt.Color(153, 255, 153));
        RadioButton_Modifier_Enfant_Oui.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Modifier_Enfant_Oui.setText("Oui");
        jPanel_Modifier.add(RadioButton_Modifier_Enfant_Oui);
        RadioButton_Modifier_Enfant_Oui.setBounds(270, 230, 47, 23);

        Combobox_Modifier_Act_Medic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Modifier.add(Combobox_Modifier_Act_Medic);
        Combobox_Modifier_Act_Medic.setBounds(270, 190, 158, 30);

        RadioButton_Modifier_Consultation_Oui.setBackground(new java.awt.Color(153, 255, 153));
        RadioButton_Modifier_Consultation_Oui.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Modifier_Consultation_Oui.setText("Oui");
        jPanel_Modifier.add(RadioButton_Modifier_Consultation_Oui);
        RadioButton_Modifier_Consultation_Oui.setBounds(270, 160, 47, 23);

        RadioButton_Modifier_Consultation_Non.setBackground(new java.awt.Color(153, 255, 153));
        RadioButton_Modifier_Consultation_Non.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Modifier_Consultation_Non.setText("Non");
        jPanel_Modifier.add(RadioButton_Modifier_Consultation_Non);
        RadioButton_Modifier_Consultation_Non.setBounds(330, 160, 51, 23);

        Combobox_Modifier_CIN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Modifier.add(Combobox_Modifier_CIN);
        Combobox_Modifier_CIN.setBounds(270, 20, 158, 30);

        txt_Modifier_Prenom.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_Modifier.add(txt_Modifier_Prenom);
        txt_Modifier_Prenom.setBounds(270, 90, 158, 20);

        combobox__Modifier_S_Orient3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Modifier.add(combobox__Modifier_S_Orient3);
        combobox__Modifier_S_Orient3.setBounds(270, 120, 158, 30);

        txt_Modifier_Nom.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_Modifier.add(txt_Modifier_Nom);
        txt_Modifier_Nom.setBounds(270, 60, 158, 20);

        jPanel_Ajouter_Pationt.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setText("CIN :");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel7.setText("Nom :");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setText("Prenom :");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel9.setText("S.Orient :");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel10.setText("Act.Med :");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel11.setText("Enfant :");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel12.setText("Sexe :");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel13.setText("Observation :");

        txt_CIN.setBackground(new java.awt.Color(0, 204, 204));

        txt_Nom.setBackground(new java.awt.Color(0, 204, 204));
        txt_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomActionPerformed(evt);
            }
        });

        txt_Prenom.setBackground(new java.awt.Color(0, 204, 204));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel14.setText("Consultation :");

        RadioButton_Enfant_Oui.setBackground(new java.awt.Color(0, 153, 153));
        RadioButton_Enfant_Oui.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Enfant_Oui.setText("Oui");

        RadioButton_Enfant_Nom.setBackground(new java.awt.Color(0, 153, 153));
        RadioButton_Enfant_Nom.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Enfant_Nom.setText("Non");

        RadioButton_Sexe_Oui.setBackground(new java.awt.Color(0, 153, 153));
        RadioButton_Sexe_Oui.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Sexe_Oui.setText("masculin ");

        RadioButton_Sexe_Nom.setBackground(new java.awt.Color(0, 153, 153));
        RadioButton_Sexe_Nom.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Sexe_Nom.setText("féminin");

        TextArea_Observation.setBackground(new java.awt.Color(0, 204, 204));
        TextArea_Observation.setColumns(20);
        TextArea_Observation.setRows(5);
        jScrollPane1.setViewportView(TextArea_Observation);

        jTable1.setForeground(new java.awt.Color(204, 255, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 9", "Title 9"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Button_Ajouter.setText("Ajouter");

        Button_Modifier.setText("Modifier");
        Button_Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ModifierActionPerformed(evt);
            }
        });

        Button_Supprimer.setText("Supprimer");
        Button_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_Supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(Button_Modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Button_Ajouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Modifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Supprimer)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        Combobx_Service_Orient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Combobx_ACT_Medical.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RadioButton_Consultation_Non.setBackground(new java.awt.Color(0, 153, 153));
        RadioButton_Consultation_Non.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Consultation_Non.setText("Non");

        RadioButton_Consultation_Oui.setBackground(new java.awt.Color(0, 153, 153));
        RadioButton_Consultation_Oui.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        RadioButton_Consultation_Oui.setText("Oui");

        jLabel_nouveau_service_orient.setText("nouveau service orient");
        jLabel_nouveau_service_orient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_nouveau_service_orient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nouveau_service_orientMouseClicked(evt);
            }
        });

        jLabel_nouveau_Acts.setText("nouveau Acts");
        jLabel_nouveau_Acts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_nouveau_Acts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nouveau_ActsMouseClicked(evt);
            }
        });

        Combobx_ID_Bererent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel15.setText("ID berderent :");

        jLabel_nouveau_ID_berderent.setText("nouveau ID berderent");
        jLabel_nouveau_ID_berderent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_nouveau_ID_berderent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nouveau_ID_berderentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Ajouter_PationtLayout = new javax.swing.GroupLayout(jPanel_Ajouter_Pationt);
        jPanel_Ajouter_Pationt.setLayout(jPanel_Ajouter_PationtLayout);
        jPanel_Ajouter_PationtLayout.setHorizontalGroup(
            jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(43, 43, 43)
                .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButton_Enfant_Oui)
                            .addComponent(RadioButton_Sexe_Oui))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButton_Enfant_Nom)
                            .addComponent(RadioButton_Sexe_Nom)))
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addComponent(RadioButton_Consultation_Oui)
                        .addGap(18, 18, 18)
                        .addComponent(RadioButton_Consultation_Non))
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Combobx_ID_Bererent, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_CIN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Nom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Prenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combobx_Service_Orient, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Combobx_ACT_Medical, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE))
                        .addGap(18, 25, Short.MAX_VALUE)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nouveau_Acts)
                            .addComponent(jLabel_nouveau_service_orient)
                            .addComponent(jLabel_nouveau_ID_berderent))))
                .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1102, Short.MAX_VALUE))
        );
        jPanel_Ajouter_PationtLayout.setVerticalGroup(
            jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Ajouter_PationtLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combobx_ID_Bererent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel_nouveau_ID_berderent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addComponent(txt_CIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combobx_Service_Orient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nouveau_service_orient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioButton_Consultation_Oui)
                            .addComponent(RadioButton_Consultation_Non))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButton_Enfant_Nom)
                            .addComponent(RadioButton_Enfant_Oui, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioButton_Sexe_Nom)
                            .addComponent(RadioButton_Sexe_Oui, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Combobx_ACT_Medical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nouveau_Acts))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel_Ajouter_PationtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Ajouter_PationtLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        Panel_Entit_Modifier.setBackground(new java.awt.Color(0, 204, 204));
        Panel_Entit_Modifier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Gestion Modifer");
        Panel_Entit_Modifier.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        Panel_Entit_Ajouter.setBackground(new java.awt.Color(0, 204, 204));
        Panel_Entit_Ajouter.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setText("Gestion Pointage");
        Panel_Entit_Ajouter.add(jLabel2);
        jLabel2.setBounds(470, 20, 201, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Modifier, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addComponent(Panel_Entit_Modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Ajouter_Pationt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Entit_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_Entit_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Ajouter_Pationt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_Entit_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ModifierActionPerformed
        jPanel_Ajouter_Pationt.setVisible(false);
        jPanel_Modifier.setVisible(true);        
        Panel_Entit_Ajouter.setVisible(false);
        Panel_Entit_Modifier.setVisible(true);
        this.setSize(620, 600);
        visibile1();
     
        
    }//GEN-LAST:event_Button_ModifierActionPerformed

    private void Button_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_enregistrerActionPerformed
       jPanel_Modifier.setVisible(false);
        jPanel_Ajouter_Pationt.setVisible(true);
        Panel_Entit_Modifier.setVisible(false);
        Panel_Entit_Ajouter.setVisible(true);
        Panel_Entit_Modifier.setVisible(false);
        this.setSize(1105, 600);
    }//GEN-LAST:event_Button_enregistrerActionPerformed

    public void visibile()
    {
        jPanel_Modifier.setBackground(new java.awt.Color(255,51,102));
        txt_Modifier_Nom.setVisible(false);
        txt_Modifier_Prenom.setVisible(false);
        combobox__Modifier_S_Orient3.setVisible(false);
        RadioButton_Modifier_Consultation_Oui.setVisible(false);
        RadioButton_Modifier_Consultation_Non.setVisible(false);
        Combobox_Modifier_Act_Medic.setVisible(false);
        RadioButton_Modifier_Enfant_Oui.setVisible(false);
        RadioButton_Modifier_Enfant_Non.setVisible(false);
        RadioButton_Modifier_Sexe_Oui.setVisible(false);
        RadioButton_Modifier_Sexe_Non.setVisible(false);
        TextArea_Modifier_Observation.setVisible(false);
        
    }
       public void visibile1()
    {
        jPanel_Modifier.setBackground(new java.awt.Color(153,255,153));
        txt_Modifier_Nom.setVisible(true);
        txt_Modifier_Prenom.setVisible(true);
        combobox__Modifier_S_Orient3.setVisible(true);
        RadioButton_Modifier_Consultation_Oui.setVisible(true);
        RadioButton_Modifier_Consultation_Non.setVisible(true);
        Combobox_Modifier_Act_Medic.setVisible(true);
        RadioButton_Modifier_Enfant_Oui.setVisible(true);
        RadioButton_Modifier_Enfant_Non.setVisible(true);
        RadioButton_Modifier_Sexe_Oui.setVisible(true);
        RadioButton_Modifier_Sexe_Non.setVisible(true);
        
    }
    private void Button_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SupprimerActionPerformed
        jPanel_Ajouter_Pationt.setVisible(false);
        jPanel_Modifier.setVisible(true);        
        Panel_Entit_Ajouter.setVisible(false);
        Panel_Entit_Modifier.setVisible(true);
        this.setSize(620, 600);
        visibile();
        
    }//GEN-LAST:event_Button_SupprimerActionPerformed

    private void RadioButton_Modifier_Sexe_OuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_Modifier_Sexe_OuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_Modifier_Sexe_OuiActionPerformed

    private void txt_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomActionPerformed

    private void jLabel_nouveau_ID_berderentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nouveau_ID_berderentMouseClicked
          
          JFrame_Borderentt form=new JFrame_Borderentt();
          form.setVisible(true);
          form.pack();
          form.setLocationRelativeTo(null);
          this.setVisible(false);
    }//GEN-LAST:event_jLabel_nouveau_ID_berderentMouseClicked

    private void jLabel_nouveau_service_orientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nouveau_service_orientMouseClicked
          JFrame_S_orient__Act_Medi form=new JFrame_S_orient__Act_Medi();
          form.setVisible(true);
          form.pack();
          form.setLocationRelativeTo(null);
          this.setVisible(false);
          form.setSize(500, 500);
    }//GEN-LAST:event_jLabel_nouveau_service_orientMouseClicked

    private void jLabel_nouveau_ActsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nouveau_ActsMouseClicked

          JFrame_Act_Medical form=new JFrame_Act_Medical();
          form.setVisible(true);
          form.pack();
          form.setLocationRelativeTo(null);
          this.setVisible(false);
          form.setSize(500, 500);
    }//GEN-LAST:event_jLabel_nouveau_ActsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Pationt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Pationt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Pationt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Pationt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Pationt().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Ajouter;
    private javax.swing.JButton Button_Modifier;
    private javax.swing.JButton Button_Supprimer;
    private javax.swing.JButton Button_enregistrer;
    private javax.swing.JComboBox Combobox_Modifier_Act_Medic;
    private javax.swing.JComboBox Combobox_Modifier_CIN;
    private javax.swing.JComboBox Combobx_ACT_Medical;
    private javax.swing.JComboBox Combobx_ID_Bererent;
    private javax.swing.JComboBox Combobx_Service_Orient;
    private javax.swing.JPanel Panel_Entit_Ajouter;
    private javax.swing.JPanel Panel_Entit_Modifier;
    private javax.swing.JRadioButton RadioButton_Consultation_Non;
    private javax.swing.JRadioButton RadioButton_Consultation_Oui;
    private javax.swing.JRadioButton RadioButton_Enfant_Nom;
    private javax.swing.JRadioButton RadioButton_Enfant_Oui;
    private javax.swing.JRadioButton RadioButton_Modifier_Consultation_Non;
    private javax.swing.JRadioButton RadioButton_Modifier_Consultation_Oui;
    private javax.swing.JRadioButton RadioButton_Modifier_Enfant_Non;
    private javax.swing.JRadioButton RadioButton_Modifier_Enfant_Oui;
    private javax.swing.JRadioButton RadioButton_Modifier_Sexe_Non;
    private javax.swing.JRadioButton RadioButton_Modifier_Sexe_Oui;
    private javax.swing.JRadioButton RadioButton_Sexe_Nom;
    private javax.swing.JRadioButton RadioButton_Sexe_Oui;
    private javax.swing.JTextArea TextArea_Modifier_Observation;
    private javax.swing.JTextArea TextArea_Observation;
    private javax.swing.JComboBox combobox__Modifier_S_Orient3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_nouveau_Acts;
    private javax.swing.JLabel jLabel_nouveau_ID_berderent;
    private javax.swing.JLabel jLabel_nouveau_service_orient;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Ajouter_Pationt;
    private javax.swing.JPanel jPanel_Modifier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_CIN;
    private javax.swing.JTextField txt_Modifier_Nom;
    private javax.swing.JTextField txt_Modifier_Prenom;
    private javax.swing.JTextField txt_Nom;
    private javax.swing.JTextField txt_Prenom;
    // End of variables declaration//GEN-END:variables
}
